server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://3.34.192.220:3306/demo_db
    username: root 
    password: roottest
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
